version: "3.9"
services:
  back:
    build: .
    ports:
      - "8080:8080"
      - "5555:5555"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: postgres
      POSTGRES_USER_NAME: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      - db

  db:
#    image: postgres:latest
    image: db_joker:1
    ports:
      - "5437:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    command: -p 5432

  pgAdmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin