# add environment variables to start via Idea -> POSTGRES_DATABASE=postgres;POSTGRES_HOST=localhost;POSTGRES_PASSWORD=postgres;POSTGRES_PORT=5435;POSTGRES_USER_NAME=postgres

batch_insertion:
  batch_size: 100000

spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        generate_statistics: true
        ddl-auto: validate
        jdbc:
          batch_size: ${batch_insertion.batch_size}
#        format_sql: false
    open-in-view: false
#  sql:
#    init:
#      mode: never
  datasource:
    username: ${POSTGRES_USER_NAME}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?stringtype=unspecified
    hikari:
      schema: "test_insertion"
#      dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  flyway:
    enabled: true
    baseline-on-migrate: true
    sql-migration-prefix: #empty prefix
    validate-migration-naming: true
    schemas: "test_insertion"
